//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoJungle.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal en() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AutoJungle.Resource.en", typeof(en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S7-AutoJungle.
        /// </summary>
        internal static string AutoJungle {
            get {
                return ResourceManager.GetString("AutoJungle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This champion is not supported!.
        /// </summary>
        internal static string ChampNotSupported {
            get {
                return ResourceManager.GetString("ChampNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print to console.
        /// </summary>
        internal static string debug {
            get {
                return ResourceManager.GetString("debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug.
        /// </summary>
        internal static string dsettings {
            get {
                return ResourceManager.GetString("dsettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recall on HP(%).
        /// </summary>
        internal static string HealtToBack {
            get {
                return ResourceManager.GetString("HealtToBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jungle settings.
        /// </summary>
        internal static string jsettings {
            get {
                return ResourceManager.GetString("jsettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This map is not supported!.
        /// </summary>
        internal static string MapNotSupported {
            get {
                return ResourceManager.GetString("MapNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have smite!.
        /// </summary>
        internal static string NoSmite {
            get {
                return ResourceManager.GetString("NoSmite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show GameState.
        /// </summary>
        internal static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
    }
}
